/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferralIdRouteImport } from './routes/referral.$id'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralIdRoute = ReferralIdRouteImport.update({
  id: '/referral/$id',
  path: '/referral/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/referral/$id': typeof ReferralIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/referral/$id': typeof ReferralIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/referral/$id': typeof ReferralIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard/referrals' | '/referral/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard/referrals' | '/referral/$id'
  id: '__root__' | '/' | '/login' | '/dashboard/referrals' | '/referral/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  ReferralIdRoute: typeof ReferralIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral/$id': {
      id: '/referral/$id'
      path: '/referral/$id'
      fullPath: '/referral/$id'
      preLoaderRoute: typeof ReferralIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  ReferralIdRoute: ReferralIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
